# Generated by Django 3.1.7 on 2021-03-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="picture_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
